// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// compute_cov
Rcpp::List compute_cov(int i, int l1, int l2, int K, arma::vec meanE, arma::mat muhats, arma::mat deltainv, arma::vec eta, arma::mat theta, arma::mat zeta, arma::mat Ipq);
RcppExport SEXP _grdpg_compute_cov(SEXP iSEXP, SEXP l1SEXP, SEXP l2SEXP, SEXP KSEXP, SEXP meanESEXP, SEXP muhatsSEXP, SEXP deltainvSEXP, SEXP etaSEXP, SEXP thetaSEXP, SEXP zetaSEXP, SEXP IpqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type l1(l1SEXP);
    Rcpp::traits::input_parameter< int >::type l2(l2SEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type meanE(meanESEXP);
    Rcpp::traits::input_parameter< arma::mat >::type muhats(muhatsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type deltainv(deltainvSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ipq(IpqSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_cov(i, l1, l2, K, meanE, muhats, deltainv, eta, theta, zeta, Ipq));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_grdpg_compute_cov", (DL_FUNC) &_grdpg_compute_cov, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_grdpg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
